// webapp/components/Marquee.tsx
import { Box, type BoxProps, Flex } from '@radix-ui/themes'
import { Heading } from './radix/Heading'

interface MarqueeProps {
  text: string
  repeat?: number
}

export const Marquee: React.FC<React.PropsWithChildren<MarqueeProps> & BoxProps> = ({
  text,
  repeat = 10,
  children,
  ...props
}) => {
  return (
    <Box overflow="hidden" className="relative w-full" {...props}>
      <Flex direction="row" align="start" gap="0">
        {Array(repeat)
          .fill(0)
          .map((_, i) => (
            <Heading
              key={i}
              size="9"
              color="gray"
              className="animate-[marquee_10s_linear_infinite] select-none whitespace-nowrap pb-2 uppercase opacity-20 md:pb-3"
            >
              <em>{text}&nbsp;</em>
            </Heading>
          ))}
      </Flex>
      <Box position="absolute" top="0" width="100%">
        {children}
      </Box>
    </Box>
  )
}

// app/src/lib/components/Marquee.svelte
<script>
  export let text = ''
  export let repeat = 10
  export let reverse = false
</script>

<div
  class="absolute top-0 left-0 flex gap-2 w-full opacity-15 overflow-hidden text-inherit italic select-none whitespace-nowrap
    {reverse ? '*:animate-[marquee_25s_linear_reverse_infinite]' : '*:animate-[marquee_25s_linear_infinite]'}">
  {#each { length: repeat } as _}
    <h1>{text}</h1>
  {/each}
</div>

<style>
  @keyframes -global-marquee {
    0% {
      transform: translateX(0%);
    }
    100% {
      transform: translateX(-100%);
    }
  }
</style>
